# Generated by Django 4.1.1 on 2022-10-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horoscope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=15, verbose_name='Дата')),
                ('sign', models.CharField(max_length=20, verbose_name='Знак зодиака')),
                ('horoscope_text', models.TextField(verbose_name='Гороскоп')),
            ],
        ),
    ]
