# Generated by Django 4.1.1 on 2022-10-03 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zodiac', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horoscope',
            options={'verbose_name': 'Гороскопы', 'verbose_name_plural': 'Гороскоп'},
        ),
    ]
